
User.create(RandomUser.fetch)
User.create(RandomUser.fetch)
User.create(RandomUser.fetch)
User.create(RandomUser.fetch)
User.create(RandomUser.fetch)
User.create(RandomUser.fetch)
User.create(RandomUser.fetch)
User.create(RandomUser.fetch)
User.create(RandomUser.fetch)
User.create(RandomUser.fetch)
